# Generated by Django 4.0.3 on 2022-03-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.restaurant'),
            preserve_default=False,
        ),
    ]
