# Generated by Django 4.0.3 on 2022-03-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='code',
        ),
        migrations.AddField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, default=11, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
