# Generated by Django 4.0.3 on 2022-03-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_table_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='qr_code',
        ),
    ]
