# Generated by Django 4.0.3 on 2022-03-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_menu_category_alter_menucategory_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='description',
            field=models.TextField(default='Спагетти, кальмары, креветки, вонголе, помидоры, томатный-соус, зелень'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu_images'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='price',
            field=models.IntegerField(default=2290),
        ),
    ]
