# Generated by Django 4.0.3 on 2022-03-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_menucategory_description_menucategory_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='price',
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='Спагетти, кальмары, креветки, вонголе, помидоры, томатный-соус, зелень'),
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu_images'),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=2290),
        ),
    ]
