# Generated by Django 4.0.3 on 2022-04-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('api', '0012_alter_menu_description_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='employees',
            field=models.ManyToManyField(related_name='restaurants', to='user_management.employee'),
        ),
    ]
