# Generated by Django 4.0.3 on 2022-04-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('api', '0015_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='user',
            new_name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('employee', 'restaurant')},
        ),
    ]
