# Generated by Django 4.0.3 on 2022-04-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
