# Generated by Django 4.0.3 on 2022-04-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_remove_user_phone'),
        ('api', '0018_delete_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_restaurants', to='user_management.employee'),
        ),
    ]
