# Generated by Django 4.0.2 on 2022-03-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategories',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
