# Generated by Django 4.0.2 on 2022-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_maincategories_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategories',
            name='is_published',
        ),
        migrations.AddField(
            model_name='maincategories',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
