# Generated by Django 4.0.2 on 2022-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_maincategories_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategories',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maincategories',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='maincategories',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
