# Generated by Django 4.0.2 on 2022-03-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_upload_maincategories_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategories',
            options={'ordering': ['name'], 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='maincategories',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='maincategories',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='maincategories',
            name='time_update',
        ),
        migrations.AddField(
            model_name='maincategories',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='maincategories',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='maincategories',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/', verbose_name='Картинка'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование продукта')),
                ('picture', models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/', verbose_name='Картинка')),
                ('title', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.maincategories', verbose_name='Товары по катергорию')),
            ],
        ),
    ]
