# Generated by Django 4.0.2 on 2022-03-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_maincategories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id'], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
